"""Generated from Smithy shape ``com.amazonaws.qconnect#OrchestrationAIAgentConfiguration``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_qconnect.types.generic_arn
    import capo_qconnect.types.json_document_list
    import capo_qconnect.types.multi_agent_configuration_list
    import capo_qconnect.types.non_empty_string
    import capo_qconnect.types.tool_configuration_list
    import capo_qconnect.types.uuid_with_qualifier


class OrchestrationAIAgentConfiguration(TypedDict, closed=True):
    orchestration_ai_prompt_id: NotRequired[
        "capo_qconnect.types.uuid_with_qualifier.UuidWithQualifier"
    ]
    """<p>The AI Prompt identifier used by the Orchestration AI Agent.</p>"""
    orchestration_ai_guardrail_id: NotRequired[
        "capo_qconnect.types.uuid_with_qualifier.UuidWithQualifier"
    ]
    """<p>The AI Guardrail identifier used by the Orchestration AI Agent.</p>"""
    tool_configurations: NotRequired[
        "capo_qconnect.types.tool_configuration_list.ToolConfigurationList"
    ]
    """<p>The tool configurations used by the Orchestration AI Agent.</p>"""
    multi_agent_configurations: NotRequired[
        "capo_qconnect.types.multi_agent_configuration_list.MultiAgentConfigurationList"
    ]
    """<p>The collaborator agents that the Orchestration AI Agent can work with. Each entry defines another agent that the orchestrator either delegates to or hands the conversation off to.</p>"""
    connect_instance_arn: NotRequired["capo_qconnect.types.generic_arn.GenericArn"]
    """<p>The Amazon Resource Name (ARN) of the Amazon Connect instance used by the Orchestration AI Agent.</p>"""
    locale: NotRequired["capo_qconnect.types.non_empty_string.NonEmptyString"]
    """<p>The locale setting for the Orchestration AI Agent.</p>"""
    input_schemas: NotRequired[
        "capo_qconnect.types.json_document_list.JSONDocumentList"
    ]
    """<p>The JSON schemas that define the structure of the structured data input accepted by the Orchestration AI Agent. The data in a <code>DATA</code> message sent to the agent is validated against these schemas. You can specify at most one schema.</p>"""
    output_schemas: NotRequired[
        "capo_qconnect.types.json_document_list.JSONDocumentList"
    ]
    """<p>The JSON schemas that define the structure of the structured output generated by the Orchestration AI Agent. You can specify at most one schema.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: OrchestrationAIAgentConfiguration) -> dict:
    out: dict = {}
    if "orchestration_ai_prompt_id" in value:
        out["orchestrationAIPromptId"] = value["orchestration_ai_prompt_id"]
    if "orchestration_ai_guardrail_id" in value:
        out["orchestrationAIGuardrailId"] = value["orchestration_ai_guardrail_id"]
    if "tool_configurations" in value:
        import capo_qconnect.types.tool_configuration_list

        out["toolConfigurations"] = (
            capo_qconnect.types.tool_configuration_list.serialize_json(
                value["tool_configurations"]
            )
        )
    if "multi_agent_configurations" in value:
        import capo_qconnect.types.multi_agent_configuration_list

        out["multiAgentConfigurations"] = (
            capo_qconnect.types.multi_agent_configuration_list.serialize_json(
                value["multi_agent_configurations"]
            )
        )
    if "connect_instance_arn" in value:
        out["connectInstanceArn"] = value["connect_instance_arn"]
    if "locale" in value:
        out["locale"] = value["locale"]
    if "input_schemas" in value:
        import capo_qconnect.types.json_document_list

        out["inputSchemas"] = capo_qconnect.types.json_document_list.serialize_json(
            value["input_schemas"]
        )
    if "output_schemas" in value:
        import capo_qconnect.types.json_document_list

        out["outputSchemas"] = capo_qconnect.types.json_document_list.serialize_json(
            value["output_schemas"]
        )
    return out


def deserialize_json(data: dict) -> OrchestrationAIAgentConfiguration:
    out: OrchestrationAIAgentConfiguration = {}  # type: ignore[typeddict-item]
    if data.get("orchestrationAIPromptId") is not None:
        out["orchestration_ai_prompt_id"] = data["orchestrationAIPromptId"]
    if data.get("orchestrationAIGuardrailId") is not None:
        out["orchestration_ai_guardrail_id"] = data["orchestrationAIGuardrailId"]
    if data.get("toolConfigurations") is not None:
        import capo_qconnect.types.tool_configuration_list

        out["tool_configurations"] = (
            capo_qconnect.types.tool_configuration_list.deserialize_json(
                data["toolConfigurations"]
            )
        )
    if data.get("multiAgentConfigurations") is not None:
        import capo_qconnect.types.multi_agent_configuration_list

        out["multi_agent_configurations"] = (
            capo_qconnect.types.multi_agent_configuration_list.deserialize_json(
                data["multiAgentConfigurations"]
            )
        )
    if data.get("connectInstanceArn") is not None:
        out["connect_instance_arn"] = data["connectInstanceArn"]
    if data.get("locale") is not None:
        out["locale"] = data["locale"]
    if data.get("inputSchemas") is not None:
        import capo_qconnect.types.json_document_list

        out["input_schemas"] = capo_qconnect.types.json_document_list.deserialize_json(
            data["inputSchemas"]
        )
    if data.get("outputSchemas") is not None:
        import capo_qconnect.types.json_document_list

        out["output_schemas"] = capo_qconnect.types.json_document_list.deserialize_json(
            data["outputSchemas"]
        )
    return out
