"""Generated from Smithy shape ``com.amazonaws.workspacesweb#CreateDataProtectionSettingsRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_workspaces_web.types.client_token
    import capo_workspaces_web.types.description_safe
    import capo_workspaces_web.types.display_name_safe
    import capo_workspaces_web.types.encryption_context_map
    import capo_workspaces_web.types.inline_redaction_configuration
    import capo_workspaces_web.types.key_arn
    import capo_workspaces_web.types.tag_list


class CreateDataProtectionSettingsRequest(TypedDict, closed=True):
    display_name: NotRequired[
        "capo_workspaces_web.types.display_name_safe.DisplayNameSafe"
    ]
    """<p>The display name of the data protection settings.</p>"""
    description: NotRequired[
        "capo_workspaces_web.types.description_safe.DescriptionSafe"
    ]
    """<p>The description of the data protection settings.</p>"""
    tags: NotRequired["capo_workspaces_web.types.tag_list.TagList"]
    """<p>The tags to add to the data protection settings resource. A tag is a key-value pair.</p>"""
    customer_managed_key: NotRequired["capo_workspaces_web.types.key_arn.keyArn"]
    """<p>The custom managed key of the data protection settings.</p>"""
    additional_encryption_context: NotRequired[
        "capo_workspaces_web.types.encryption_context_map.EncryptionContextMap"
    ]
    """<p>Additional encryption context of the data protection settings.</p>"""
    inline_redaction_configuration: NotRequired[
        "capo_workspaces_web.types.inline_redaction_configuration.InlineRedactionConfiguration"
    ]
    """<p>The inline redaction configuration of the data protection settings that will be applied to all sessions.</p>"""
    client_token: NotRequired["capo_workspaces_web.types.client_token.ClientToken"]
    """<p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: CreateDataProtectionSettingsRequest) -> dict:
    out: dict = {}
    if "display_name" in value:
        out["displayName"] = value["display_name"]
    if "description" in value:
        out["description"] = value["description"]
    if "tags" in value:
        import capo_workspaces_web.types.tag_list

        out["tags"] = capo_workspaces_web.types.tag_list.serialize_json(value["tags"])
    if "customer_managed_key" in value:
        out["customerManagedKey"] = value["customer_managed_key"]
    if "additional_encryption_context" in value:
        import capo_workspaces_web.types.encryption_context_map

        out["additionalEncryptionContext"] = (
            capo_workspaces_web.types.encryption_context_map.serialize_json(
                value["additional_encryption_context"]
            )
        )
    if "inline_redaction_configuration" in value:
        import capo_workspaces_web.types.inline_redaction_configuration

        out["inlineRedactionConfiguration"] = (
            capo_workspaces_web.types.inline_redaction_configuration.serialize_json(
                value["inline_redaction_configuration"]
            )
        )
    if "client_token" in value:
        out["clientToken"] = value["client_token"]
    return out


def deserialize_json(data: dict) -> CreateDataProtectionSettingsRequest:
    out: CreateDataProtectionSettingsRequest = {}  # type: ignore[typeddict-item]
    if data.get("displayName") is not None:
        out["display_name"] = data["displayName"]
    if data.get("description") is not None:
        out["description"] = data["description"]
    if data.get("tags") is not None:
        import capo_workspaces_web.types.tag_list

        out["tags"] = capo_workspaces_web.types.tag_list.deserialize_json(data["tags"])
    if data.get("customerManagedKey") is not None:
        out["customer_managed_key"] = data["customerManagedKey"]
    if data.get("additionalEncryptionContext") is not None:
        import capo_workspaces_web.types.encryption_context_map

        out["additional_encryption_context"] = (
            capo_workspaces_web.types.encryption_context_map.deserialize_json(
                data["additionalEncryptionContext"]
            )
        )
    if data.get("inlineRedactionConfiguration") is not None:
        import capo_workspaces_web.types.inline_redaction_configuration

        out["inline_redaction_configuration"] = (
            capo_workspaces_web.types.inline_redaction_configuration.deserialize_json(
                data["inlineRedactionConfiguration"]
            )
        )
    if data.get("clientToken") is not None:
        out["client_token"] = data["clientToken"]
    return out
