"""Generated from Smithy shape ``com.amazonaws.workspacesweb#CreateIpAccessSettingsRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_workspaces_web.errors import DeserializationError

if TYPE_CHECKING:
    import capo_workspaces_web.types.client_token
    import capo_workspaces_web.types.description
    import capo_workspaces_web.types.display_name
    import capo_workspaces_web.types.encryption_context_map
    import capo_workspaces_web.types.ip_rule_list
    import capo_workspaces_web.types.key_arn
    import capo_workspaces_web.types.tag_list


class CreateIpAccessSettingsRequest(TypedDict, closed=True):
    display_name: NotRequired["capo_workspaces_web.types.display_name.DisplayName"]
    """<p>The display name of the IP access settings.</p>"""
    description: NotRequired["capo_workspaces_web.types.description.Description"]
    """<p>The description of the IP access settings.</p>"""
    tags: NotRequired["capo_workspaces_web.types.tag_list.TagList"]
    """<p>The tags to add to the IP access settings resource. A tag is a key-value pair.</p>"""
    customer_managed_key: NotRequired["capo_workspaces_web.types.key_arn.keyArn"]
    """<p>The custom managed key of the IP access settings.</p>"""
    additional_encryption_context: NotRequired[
        "capo_workspaces_web.types.encryption_context_map.EncryptionContextMap"
    ]
    """<p>Additional encryption context of the IP access settings.</p>"""
    ip_rules: "capo_workspaces_web.types.ip_rule_list.IpRuleList"
    """<p>The IP rules of the IP access settings.</p>"""
    client_token: NotRequired["capo_workspaces_web.types.client_token.ClientToken"]
    """<p>A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. Idempotency ensures that an API request completes only once. With an idempotent request, if the original request completes successfully, subsequent retries with the same client token returns the result from the original successful request. </p> <p>If you do not specify a client token, one is automatically generated by the Amazon Web Services SDK.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: CreateIpAccessSettingsRequest) -> dict:
    out: dict = {}
    if "display_name" in value:
        out["displayName"] = value["display_name"]
    if "description" in value:
        out["description"] = value["description"]
    if "tags" in value:
        import capo_workspaces_web.types.tag_list

        out["tags"] = capo_workspaces_web.types.tag_list.serialize_json(value["tags"])
    if "customer_managed_key" in value:
        out["customerManagedKey"] = value["customer_managed_key"]
    if "additional_encryption_context" in value:
        import capo_workspaces_web.types.encryption_context_map

        out["additionalEncryptionContext"] = (
            capo_workspaces_web.types.encryption_context_map.serialize_json(
                value["additional_encryption_context"]
            )
        )
    import capo_workspaces_web.types.ip_rule_list

    out["ipRules"] = capo_workspaces_web.types.ip_rule_list.serialize_json(
        value["ip_rules"]
    )
    if "client_token" in value:
        out["clientToken"] = value["client_token"]
    return out


def deserialize_json(data: dict) -> CreateIpAccessSettingsRequest:
    out: CreateIpAccessSettingsRequest = {}  # type: ignore[typeddict-item]
    if data.get("displayName") is not None:
        out["display_name"] = data["displayName"]
    if data.get("description") is not None:
        out["description"] = data["description"]
    if data.get("tags") is not None:
        import capo_workspaces_web.types.tag_list

        out["tags"] = capo_workspaces_web.types.tag_list.deserialize_json(data["tags"])
    if data.get("customerManagedKey") is not None:
        out["customer_managed_key"] = data["customerManagedKey"]
    if data.get("additionalEncryptionContext") is not None:
        import capo_workspaces_web.types.encryption_context_map

        out["additional_encryption_context"] = (
            capo_workspaces_web.types.encryption_context_map.deserialize_json(
                data["additionalEncryptionContext"]
            )
        )
    if data.get("ipRules") is not None:
        import capo_workspaces_web.types.ip_rule_list

        out["ip_rules"] = capo_workspaces_web.types.ip_rule_list.deserialize_json(
            data["ipRules"]
        )
    else:
        raise DeserializationError("CreateIpAccessSettingsRequest.ip_rules required")
    if data.get("clientToken") is not None:
        out["client_token"] = data["clientToken"]
    return out
