"""Generated from Smithy shape ``com.amazonaws.bedrockagentcore#ToolDescriptionOutput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_bedrock_agentcore.errors import DeserializationError

if TYPE_CHECKING:
    import capo_bedrock_agentcore.types.recommendation_explanation
    import capo_bedrock_agentcore.types.recommendation_tool_name
    import capo_bedrock_agentcore.types.tool_description_text


class ToolDescriptionOutput(TypedDict, closed=True):
    tool_name: (
        "capo_bedrock_agentcore.types.recommendation_tool_name.RecommendationToolName"
    )
    """<p>The name of the tool.</p>"""
    recommended_tool_description: NotRequired[
        "capo_bedrock_agentcore.types.tool_description_text.ToolDescriptionText"
    ]
    """<p>The optimized tool description text generated by the recommendation.</p>"""
    explanation: NotRequired[
        "capo_bedrock_agentcore.types.recommendation_explanation.RecommendationExplanation"
    ]
    """<p>An explanation of why the recommendation was generated for this tool and what patterns were identified in the agent traces.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: ToolDescriptionOutput) -> dict:
    out: dict = {}
    out["toolName"] = value["tool_name"]
    if "recommended_tool_description" in value:
        out["recommendedToolDescription"] = value["recommended_tool_description"]
    if "explanation" in value:
        out["explanation"] = value["explanation"]
    return out


def deserialize_json(data: dict) -> ToolDescriptionOutput:
    out: ToolDescriptionOutput = {}  # type: ignore[typeddict-item]
    if data.get("toolName") is not None:
        out["tool_name"] = data["toolName"]
    else:
        raise DeserializationError("ToolDescriptionOutput.tool_name required")
    if data.get("recommendedToolDescription") is not None:
        out["recommended_tool_description"] = data["recommendedToolDescription"]
    if data.get("explanation") is not None:
        out["explanation"] = data["explanation"]
    return out
