"""Generated from Smithy shape ``com.amazonaws.appsync#SourceApiAssociationSummary``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_appsync.types.string


class SourceApiAssociationSummary(TypedDict, closed=True):
    association_id: NotRequired["capo_appsync.types.string.String"]
    """<p>The ID generated by the AppSync service for the source API association.</p>"""
    association_arn: NotRequired["capo_appsync.types.string.String"]
    """<p>The Amazon Resource Name (ARN) of the source API association.</p>"""
    source_api_id: NotRequired["capo_appsync.types.string.String"]
    """<p>The ID of the AppSync source API.</p>"""
    source_api_arn: NotRequired["capo_appsync.types.string.String"]
    """<p>The Amazon Resource Name (ARN) of the AppSync Source API.</p>"""
    merged_api_id: NotRequired["capo_appsync.types.string.String"]
    """<p>The ID of the AppSync Merged API.</p>"""
    merged_api_arn: NotRequired["capo_appsync.types.string.String"]
    """<p>The Amazon Resource Name (ARN) of the AppSync Merged API.</p>"""
    description: NotRequired["capo_appsync.types.string.String"]
    """<p>The description field.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: SourceApiAssociationSummary) -> dict:
    out: dict = {}
    if "association_id" in value:
        out["associationId"] = value["association_id"]
    if "association_arn" in value:
        out["associationArn"] = value["association_arn"]
    if "source_api_id" in value:
        out["sourceApiId"] = value["source_api_id"]
    if "source_api_arn" in value:
        out["sourceApiArn"] = value["source_api_arn"]
    if "merged_api_id" in value:
        out["mergedApiId"] = value["merged_api_id"]
    if "merged_api_arn" in value:
        out["mergedApiArn"] = value["merged_api_arn"]
    if "description" in value:
        out["description"] = value["description"]
    return out


def deserialize_json(data: dict) -> SourceApiAssociationSummary:
    out: SourceApiAssociationSummary = {}  # type: ignore[typeddict-item]
    if data.get("associationId") is not None:
        out["association_id"] = data["associationId"]
    if data.get("associationArn") is not None:
        out["association_arn"] = data["associationArn"]
    if data.get("sourceApiId") is not None:
        out["source_api_id"] = data["sourceApiId"]
    if data.get("sourceApiArn") is not None:
        out["source_api_arn"] = data["sourceApiArn"]
    if data.get("mergedApiId") is not None:
        out["merged_api_id"] = data["mergedApiId"]
    if data.get("mergedApiArn") is not None:
        out["merged_api_arn"] = data["mergedApiArn"]
    if data.get("description") is not None:
        out["description"] = data["description"]
    return out
