"""Generated from Smithy shape ``com.amazonaws.trustedadvisor#OrganizationRecommendation``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_trustedadvisor.errors import DeserializationError

if TYPE_CHECKING:
    import datetime

    import capo_trustedadvisor.types.organization_recommendation_arn
    import capo_trustedadvisor.types.recommendation_aws_service_list
    import capo_trustedadvisor.types.recommendation_lifecycle_stage
    import capo_trustedadvisor.types.recommendation_pillar_list
    import capo_trustedadvisor.types.recommendation_pillar_specific_aggregates
    import capo_trustedadvisor.types.recommendation_resources_aggregates
    import capo_trustedadvisor.types.recommendation_source
    import capo_trustedadvisor.types.recommendation_status
    import capo_trustedadvisor.types.recommendation_type
    import capo_trustedadvisor.types.recommendation_update_reason
    import capo_trustedadvisor.types.update_recommendation_lifecycle_stage_reason_code


class OrganizationRecommendation(TypedDict, closed=True):
    id: "str"
    """<p>The ID which identifies where the Recommendation was produced</p>"""
    type: "capo_trustedadvisor.types.recommendation_type.RecommendationType"
    """<p>Whether the Recommendation was automated or generated by AWS Trusted Advisor Priority</p>"""
    check_arn: NotRequired["str"]
    """<p>The AWS Trusted Advisor Check ARN that relates to the Recommendation</p>"""
    status: "capo_trustedadvisor.types.recommendation_status.RecommendationStatus"
    """<p>The status of the Recommendation</p>"""
    lifecycle_stage: NotRequired[
        "capo_trustedadvisor.types.recommendation_lifecycle_stage.RecommendationLifecycleStage"
    ]
    """<p>The lifecycle stage from AWS Trusted Advisor Priority</p>"""
    pillars: (
        "capo_trustedadvisor.types.recommendation_pillar_list.RecommendationPillarList"
    )
    """<p>The Pillars that the Recommendation is optimizing</p>"""
    source: "capo_trustedadvisor.types.recommendation_source.RecommendationSource"
    """<p>The source of the Recommendation</p>"""
    aws_services: NotRequired[
        "capo_trustedadvisor.types.recommendation_aws_service_list.RecommendationAwsServiceList"
    ]
    """<p>The AWS Services that the Recommendation applies to</p>"""
    name: "str"
    """<p>The name of the AWS Trusted Advisor Recommendation</p>"""
    resources_aggregates: "capo_trustedadvisor.types.recommendation_resources_aggregates.RecommendationResourcesAggregates"
    """<p>An aggregation of all resources</p>"""
    pillar_specific_aggregates: NotRequired[
        "capo_trustedadvisor.types.recommendation_pillar_specific_aggregates.RecommendationPillarSpecificAggregates"
    ]
    """<p>The pillar aggregations for cost savings</p>"""
    created_at: NotRequired["datetime.datetime"]
    """<p>When the Recommendation was created, if created by AWS Trusted Advisor Priority</p>"""
    last_updated_at: NotRequired["datetime.datetime"]
    """<p>When the Recommendation was last updated</p>"""
    arn: "capo_trustedadvisor.types.organization_recommendation_arn.OrganizationRecommendationArn"
    """<p>The ARN of the Recommendation</p>"""
    description: "str"
    """<p>A description for AWS Trusted Advisor recommendations</p>"""
    created_by: NotRequired["str"]
    """<p>The creator, if created by AWS Trusted Advisor Priority</p>"""
    updated_on_behalf_of: NotRequired["str"]
    """<p>The person on whose behalf a Technical Account Manager (TAM) updated the recommendation. This information is only available when a Technical Account Manager takes an action on a recommendation managed by AWS Trusted Advisor Priority </p>"""
    updated_on_behalf_of_job_title: NotRequired["str"]
    """<p>The job title of the person on whose behalf a Technical Account Manager (TAM) updated the recommendation. This information is only available when a Technical Account Manager takes an action on a recommendation managed by AWS Trusted Advisor Priority </p>"""
    update_reason: NotRequired[
        "capo_trustedadvisor.types.recommendation_update_reason.RecommendationUpdateReason"
    ]
    """<p>Reason for the lifecycle stage change</p>"""
    update_reason_code: NotRequired[
        "capo_trustedadvisor.types.update_recommendation_lifecycle_stage_reason_code.UpdateRecommendationLifecycleStageReasonCode"
    ]
    """<p>Reason code for the lifecycle state change</p>"""
    resolved_at: NotRequired["datetime.datetime"]
    """<p>When the Recommendation was resolved</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: OrganizationRecommendation) -> dict:
    out: dict = {}
    out["id"] = value["id"]
    import capo_trustedadvisor.types.recommendation_type

    out["type"] = capo_trustedadvisor.types.recommendation_type.serialize_json(
        value["type"]
    )
    if "check_arn" in value:
        out["checkArn"] = value["check_arn"]
    import capo_trustedadvisor.types.recommendation_status

    out["status"] = capo_trustedadvisor.types.recommendation_status.serialize_json(
        value["status"]
    )
    if "lifecycle_stage" in value:
        import capo_trustedadvisor.types.recommendation_lifecycle_stage

        out["lifecycleStage"] = (
            capo_trustedadvisor.types.recommendation_lifecycle_stage.serialize_json(
                value["lifecycle_stage"]
            )
        )
    import capo_trustedadvisor.types.recommendation_pillar_list

    out["pillars"] = (
        capo_trustedadvisor.types.recommendation_pillar_list.serialize_json(
            value["pillars"]
        )
    )
    import capo_trustedadvisor.types.recommendation_source

    out["source"] = capo_trustedadvisor.types.recommendation_source.serialize_json(
        value["source"]
    )
    if "aws_services" in value:
        import capo_trustedadvisor.types.recommendation_aws_service_list

        out["awsServices"] = (
            capo_trustedadvisor.types.recommendation_aws_service_list.serialize_json(
                value["aws_services"]
            )
        )
    out["name"] = value["name"]
    import capo_trustedadvisor.types.recommendation_resources_aggregates

    out["resourcesAggregates"] = (
        capo_trustedadvisor.types.recommendation_resources_aggregates.serialize_json(
            value["resources_aggregates"]
        )
    )
    if "pillar_specific_aggregates" in value:
        import capo_trustedadvisor.types.recommendation_pillar_specific_aggregates

        out["pillarSpecificAggregates"] = (
            capo_trustedadvisor.types.recommendation_pillar_specific_aggregates.serialize_json(
                value["pillar_specific_aggregates"]
            )
        )
    if "created_at" in value:
        import capo_trustedadvisor._protocol.serialize

        out["createdAt"] = capo_trustedadvisor._protocol.serialize.fmt_date_time(
            value["created_at"]
        )
    if "last_updated_at" in value:
        import capo_trustedadvisor._protocol.serialize

        out["lastUpdatedAt"] = capo_trustedadvisor._protocol.serialize.fmt_date_time(
            value["last_updated_at"]
        )
    out["arn"] = value["arn"]
    out["description"] = value["description"]
    if "created_by" in value:
        out["createdBy"] = value["created_by"]
    if "updated_on_behalf_of" in value:
        out["updatedOnBehalfOf"] = value["updated_on_behalf_of"]
    if "updated_on_behalf_of_job_title" in value:
        out["updatedOnBehalfOfJobTitle"] = value["updated_on_behalf_of_job_title"]
    if "update_reason" in value:
        out["updateReason"] = value["update_reason"]
    if "update_reason_code" in value:
        import capo_trustedadvisor.types.update_recommendation_lifecycle_stage_reason_code

        out["updateReasonCode"] = (
            capo_trustedadvisor.types.update_recommendation_lifecycle_stage_reason_code.serialize_json(
                value["update_reason_code"]
            )
        )
    if "resolved_at" in value:
        import capo_trustedadvisor._protocol.serialize

        out["resolvedAt"] = capo_trustedadvisor._protocol.serialize.fmt_date_time(
            value["resolved_at"]
        )
    return out


def deserialize_json(data: dict) -> OrganizationRecommendation:
    out: OrganizationRecommendation = {}  # type: ignore[typeddict-item]
    if data.get("id") is not None:
        out["id"] = data["id"]
    else:
        raise DeserializationError("OrganizationRecommendation.id required")
    if data.get("type") is not None:
        import capo_trustedadvisor.types.recommendation_type

        out["type"] = capo_trustedadvisor.types.recommendation_type.deserialize_json(
            data["type"]
        )
    else:
        raise DeserializationError("OrganizationRecommendation.type required")
    if data.get("checkArn") is not None:
        out["check_arn"] = data["checkArn"]
    if data.get("status") is not None:
        import capo_trustedadvisor.types.recommendation_status

        out["status"] = (
            capo_trustedadvisor.types.recommendation_status.deserialize_json(
                data["status"]
            )
        )
    else:
        raise DeserializationError("OrganizationRecommendation.status required")
    if data.get("lifecycleStage") is not None:
        import capo_trustedadvisor.types.recommendation_lifecycle_stage

        out["lifecycle_stage"] = (
            capo_trustedadvisor.types.recommendation_lifecycle_stage.deserialize_json(
                data["lifecycleStage"]
            )
        )
    if data.get("pillars") is not None:
        import capo_trustedadvisor.types.recommendation_pillar_list

        out["pillars"] = (
            capo_trustedadvisor.types.recommendation_pillar_list.deserialize_json(
                data["pillars"]
            )
        )
    else:
        raise DeserializationError("OrganizationRecommendation.pillars required")
    if data.get("source") is not None:
        import capo_trustedadvisor.types.recommendation_source

        out["source"] = (
            capo_trustedadvisor.types.recommendation_source.deserialize_json(
                data["source"]
            )
        )
    else:
        raise DeserializationError("OrganizationRecommendation.source required")
    if data.get("awsServices") is not None:
        import capo_trustedadvisor.types.recommendation_aws_service_list

        out["aws_services"] = (
            capo_trustedadvisor.types.recommendation_aws_service_list.deserialize_json(
                data["awsServices"]
            )
        )
    if data.get("name") is not None:
        out["name"] = data["name"]
    else:
        raise DeserializationError("OrganizationRecommendation.name required")
    if data.get("resourcesAggregates") is not None:
        import capo_trustedadvisor.types.recommendation_resources_aggregates

        out["resources_aggregates"] = (
            capo_trustedadvisor.types.recommendation_resources_aggregates.deserialize_json(
                data["resourcesAggregates"]
            )
        )
    else:
        raise DeserializationError(
            "OrganizationRecommendation.resources_aggregates required"
        )
    if data.get("pillarSpecificAggregates") is not None:
        import capo_trustedadvisor.types.recommendation_pillar_specific_aggregates

        out["pillar_specific_aggregates"] = (
            capo_trustedadvisor.types.recommendation_pillar_specific_aggregates.deserialize_json(
                data["pillarSpecificAggregates"]
            )
        )
    if data.get("createdAt") is not None:
        import datetime

        out["created_at"] = datetime.datetime.fromisoformat(
            data["createdAt"].replace("Z", "+00:00")
        )
    if data.get("lastUpdatedAt") is not None:
        import datetime

        out["last_updated_at"] = datetime.datetime.fromisoformat(
            data["lastUpdatedAt"].replace("Z", "+00:00")
        )
    if data.get("arn") is not None:
        out["arn"] = data["arn"]
    else:
        raise DeserializationError("OrganizationRecommendation.arn required")
    if data.get("description") is not None:
        out["description"] = data["description"]
    else:
        raise DeserializationError("OrganizationRecommendation.description required")
    if data.get("createdBy") is not None:
        out["created_by"] = data["createdBy"]
    if data.get("updatedOnBehalfOf") is not None:
        out["updated_on_behalf_of"] = data["updatedOnBehalfOf"]
    if data.get("updatedOnBehalfOfJobTitle") is not None:
        out["updated_on_behalf_of_job_title"] = data["updatedOnBehalfOfJobTitle"]
    if data.get("updateReason") is not None:
        out["update_reason"] = data["updateReason"]
    if data.get("updateReasonCode") is not None:
        import capo_trustedadvisor.types.update_recommendation_lifecycle_stage_reason_code

        out["update_reason_code"] = (
            capo_trustedadvisor.types.update_recommendation_lifecycle_stage_reason_code.deserialize_json(
                data["updateReasonCode"]
            )
        )
    if data.get("resolvedAt") is not None:
        import datetime

        out["resolved_at"] = datetime.datetime.fromisoformat(
            data["resolvedAt"].replace("Z", "+00:00")
        )
    return out
