"""Generated from Smithy shape ``com.amazonaws.resiliencehubv2#AssessmentSummary``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_resiliencehubv2.errors import DeserializationError

if TYPE_CHECKING:
    import datetime

    import capo_resiliencehubv2.types.achievability
    import capo_resiliencehubv2.types.arn
    import capo_resiliencehubv2.types.assessment_cost
    import capo_resiliencehubv2.types.assessment_error_code
    import capo_resiliencehubv2.types.assessment_status
    import capo_resiliencehubv2.types.assessment_step
    import capo_resiliencehubv2.types.uuid


class AssessmentSummary(TypedDict, closed=True):
    assessment_id: "capo_resiliencehubv2.types.uuid.Uuid"
    """<p>The unique identifier of the assessment.</p>"""
    service_arn: "capo_resiliencehubv2.types.arn.Arn"
    assessment_status: NotRequired[
        "capo_resiliencehubv2.types.assessment_status.AssessmentStatus"
    ]
    """<p>The current status of the assessment.</p>"""
    assessment_step: NotRequired[
        "capo_resiliencehubv2.types.assessment_step.AssessmentStep"
    ]
    """<p>The current step of the assessment process.</p>"""
    total_findings: NotRequired["int"]
    """<p>The total number of findings generated by the assessment.</p>"""
    started_at: NotRequired["datetime.datetime"]
    """<p>The timestamp when the assessment started.</p>"""
    ended_at: NotRequired["datetime.datetime"]
    """<p>The timestamp when the assessment ended.</p>"""
    error_message: NotRequired["str"]
    """<p>A message describing the error if the assessment failed.</p>"""
    error_code: NotRequired[
        "capo_resiliencehubv2.types.assessment_error_code.AssessmentErrorCode"
    ]
    """<p>The error code if the assessment failed.</p>"""
    assessment_cost: NotRequired[
        "capo_resiliencehubv2.types.assessment_cost.AssessmentCost"
    ]
    """<p>The cost of the assessment.</p>"""
    billable_assessment_unit_count: NotRequired["int"]
    """<p>The number of billable assessment units consumed by the assessment.</p>"""
    achievability: NotRequired["capo_resiliencehubv2.types.achievability.Achievability"]
    """<p>The achievability results from the assessment.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: AssessmentSummary) -> dict:
    out: dict = {}
    out["assessmentId"] = value["assessment_id"]
    out["serviceArn"] = value["service_arn"]
    if "assessment_status" in value:
        import capo_resiliencehubv2.types.assessment_status

        out["assessmentStatus"] = (
            capo_resiliencehubv2.types.assessment_status.serialize_json(
                value["assessment_status"]
            )
        )
    if "assessment_step" in value:
        import capo_resiliencehubv2.types.assessment_step

        out["assessmentStep"] = (
            capo_resiliencehubv2.types.assessment_step.serialize_json(
                value["assessment_step"]
            )
        )
    if "total_findings" in value:
        out["totalFindings"] = value["total_findings"]
    if "started_at" in value:
        import capo_resiliencehubv2.types._prelude.timestamp

        out["startedAt"] = capo_resiliencehubv2.types._prelude.timestamp.serialize_json(
            value["started_at"]
        )
    if "ended_at" in value:
        import capo_resiliencehubv2.types._prelude.timestamp

        out["endedAt"] = capo_resiliencehubv2.types._prelude.timestamp.serialize_json(
            value["ended_at"]
        )
    if "error_message" in value:
        out["errorMessage"] = value["error_message"]
    if "error_code" in value:
        import capo_resiliencehubv2.types.assessment_error_code

        out["errorCode"] = (
            capo_resiliencehubv2.types.assessment_error_code.serialize_json(
                value["error_code"]
            )
        )
    if "assessment_cost" in value:
        import capo_resiliencehubv2.types.assessment_cost

        out["assessmentCost"] = (
            capo_resiliencehubv2.types.assessment_cost.serialize_json(
                value["assessment_cost"]
            )
        )
    if "billable_assessment_unit_count" in value:
        out["billableAssessmentUnitCount"] = value["billable_assessment_unit_count"]
    if "achievability" in value:
        import capo_resiliencehubv2.types.achievability

        out["achievability"] = capo_resiliencehubv2.types.achievability.serialize_json(
            value["achievability"]
        )
    return out


def deserialize_json(data: dict) -> AssessmentSummary:
    out: AssessmentSummary = {}  # type: ignore[typeddict-item]
    if data.get("assessmentId") is not None:
        out["assessment_id"] = data["assessmentId"]
    else:
        raise DeserializationError("AssessmentSummary.assessment_id required")
    if data.get("serviceArn") is not None:
        out["service_arn"] = data["serviceArn"]
    else:
        raise DeserializationError("AssessmentSummary.service_arn required")
    if data.get("assessmentStatus") is not None:
        import capo_resiliencehubv2.types.assessment_status

        out["assessment_status"] = (
            capo_resiliencehubv2.types.assessment_status.deserialize_json(
                data["assessmentStatus"]
            )
        )
    if data.get("assessmentStep") is not None:
        import capo_resiliencehubv2.types.assessment_step

        out["assessment_step"] = (
            capo_resiliencehubv2.types.assessment_step.deserialize_json(
                data["assessmentStep"]
            )
        )
    if data.get("totalFindings") is not None:
        out["total_findings"] = data["totalFindings"]
    if data.get("startedAt") is not None:
        import capo_resiliencehubv2.types._prelude.timestamp

        out["started_at"] = (
            capo_resiliencehubv2.types._prelude.timestamp.deserialize_json(
                data["startedAt"]
            )
        )
    if data.get("endedAt") is not None:
        import capo_resiliencehubv2.types._prelude.timestamp

        out["ended_at"] = (
            capo_resiliencehubv2.types._prelude.timestamp.deserialize_json(
                data["endedAt"]
            )
        )
    if data.get("errorMessage") is not None:
        out["error_message"] = data["errorMessage"]
    if data.get("errorCode") is not None:
        import capo_resiliencehubv2.types.assessment_error_code

        out["error_code"] = (
            capo_resiliencehubv2.types.assessment_error_code.deserialize_json(
                data["errorCode"]
            )
        )
    if data.get("assessmentCost") is not None:
        import capo_resiliencehubv2.types.assessment_cost

        out["assessment_cost"] = (
            capo_resiliencehubv2.types.assessment_cost.deserialize_json(
                data["assessmentCost"]
            )
        )
    if data.get("billableAssessmentUnitCount") is not None:
        out["billable_assessment_unit_count"] = data["billableAssessmentUnitCount"]
    if data.get("achievability") is not None:
        import capo_resiliencehubv2.types.achievability

        out["achievability"] = (
            capo_resiliencehubv2.types.achievability.deserialize_json(
                data["achievability"]
            )
        )
    return out
