"""Generated from Smithy shape ``com.amazonaws.identitystore#AccessDeniedException``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_identitystore.errors import ServiceError

if TYPE_CHECKING:
    import capo_identitystore.types.access_denied_exception_reason
    import capo_identitystore.types.exception_message
    import capo_identitystore.types.request_id


class AccessDeniedException_(TypedDict, closed=True):
    message: NotRequired["capo_identitystore.types.exception_message.ExceptionMessage"]
    request_id: NotRequired["capo_identitystore.types.request_id.RequestId"]
    """<p>The identifier for each request. This value is a globally unique ID that is generated by the identity store service for each sent request, and is then returned inside the exception if the request fails.</p>"""
    reason: NotRequired[
        "capo_identitystore.types.access_denied_exception_reason.AccessDeniedExceptionReason"
    ]
    """<p>Indicates the reason for an access denial when returned by KMS while accessing a Customer Managed KMS key. For non-KMS access-denied errors, this field is not included.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: AccessDeniedException_) -> dict:
    out: dict = {}
    if "message" in value:
        out["Message"] = value["message"]
    if "request_id" in value:
        out["RequestId"] = value["request_id"]
    if "reason" in value:
        import capo_identitystore.types.access_denied_exception_reason

        out["Reason"] = (
            capo_identitystore.types.access_denied_exception_reason.serialize_aws_json_1_1(
                value["reason"]
            )
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> AccessDeniedException_:
    out: AccessDeniedException_ = {}  # type: ignore[typeddict-item]
    if data.get("Message") is not None:
        out["message"] = data["Message"]
    if data.get("RequestId") is not None:
        out["request_id"] = data["RequestId"]
    if data.get("Reason") is not None:
        import capo_identitystore.types.access_denied_exception_reason

        out["reason"] = (
            capo_identitystore.types.access_denied_exception_reason.deserialize_aws_json_1_1(
                data["Reason"]
            )
        )
    return out


class AccessDeniedException(ServiceError):
    """Modeled error for Smithy shape ``com.amazonaws.identitystore#AccessDeniedException``."""

    code: str | None = "AccessDeniedException"

    def __init__(self, data: AccessDeniedException_, message: str | None = None):
        super().__init__(
            "client",
            is_throttling_error=False,
            is_retryable=False,
            code="AccessDeniedException",
            message=message if message is not None else data.get("message"),
        )
        self.data = data

    @classmethod
    def from_aws_json_1_1(
        cls, data: dict, message: str | None = None
    ) -> "AccessDeniedException":
        return cls(deserialize_aws_json_1_1(data), message)
