"""Generated from Smithy shape ``com.amazonaws.identitystore#InternalServerException``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_identitystore.errors import ServiceError

if TYPE_CHECKING:
    import capo_identitystore.types.exception_message
    import capo_identitystore.types.request_id
    import capo_identitystore.types.retry_after_seconds


class InternalServerException_(TypedDict, closed=True):
    message: NotRequired["capo_identitystore.types.exception_message.ExceptionMessage"]
    request_id: NotRequired["capo_identitystore.types.request_id.RequestId"]
    """<p>The identifier for each request. This value is a globally unique ID that is generated by the identity store service for each sent request, and is then returned inside the exception if the request fails.</p>"""
    retry_after_seconds: (
        "capo_identitystore.types.retry_after_seconds.RetryAfterSeconds"
    )
    """<p>The number of seconds to wait before retrying the next request.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: InternalServerException_) -> dict:
    out: dict = {}
    if "message" in value:
        out["Message"] = value["message"]
    if "request_id" in value:
        out["RequestId"] = value["request_id"]
    out["RetryAfterSeconds"] = value.get("retry_after_seconds", 0)
    return out


def deserialize_aws_json_1_1(data: dict) -> InternalServerException_:
    out: InternalServerException_ = {}  # type: ignore[typeddict-item]
    if data.get("Message") is not None:
        out["message"] = data["Message"]
    if data.get("RequestId") is not None:
        out["request_id"] = data["RequestId"]
    if data.get("RetryAfterSeconds") is not None:
        out["retry_after_seconds"] = data["RetryAfterSeconds"]
    else:
        out["retry_after_seconds"] = 0
    return out


class InternalServerException(ServiceError):
    """Modeled error for Smithy shape ``com.amazonaws.identitystore#InternalServerException``."""

    code: str | None = "InternalServerException"

    def __init__(self, data: InternalServerException_, message: str | None = None):
        super().__init__(
            "server",
            is_throttling_error=False,
            is_retryable=True,
            code="InternalServerException",
            message=message,
        )
        self.data = data

    @classmethod
    def from_aws_json_1_1(
        cls, data: dict, message: str | None = None
    ) -> "InternalServerException":
        return cls(deserialize_aws_json_1_1(data), message)
