"""Generated from Smithy shape ``com.amazonaws.identitystore#ValidationException``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_identitystore.errors import ServiceError

if TYPE_CHECKING:
    import capo_identitystore.types.exception_message
    import capo_identitystore.types.request_id
    import capo_identitystore.types.validation_exception_reason


class ValidationException_(TypedDict, closed=True):
    message: NotRequired["capo_identitystore.types.exception_message.ExceptionMessage"]
    request_id: NotRequired["capo_identitystore.types.request_id.RequestId"]
    """<p>The identifier for each request. This value is a globally unique ID that is generated by the identity store service for each sent request, and is then returned inside the exception if the request fails.</p>"""
    reason: NotRequired[
        "capo_identitystore.types.validation_exception_reason.ValidationExceptionReason"
    ]
    """<p>Indicates the reason for the validation error when the service is unable to access a Customer Managed KMS key. For non-KMS permission errors, this field is not included.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ValidationException_) -> dict:
    out: dict = {}
    if "message" in value:
        out["Message"] = value["message"]
    if "request_id" in value:
        out["RequestId"] = value["request_id"]
    if "reason" in value:
        import capo_identitystore.types.validation_exception_reason

        out["Reason"] = (
            capo_identitystore.types.validation_exception_reason.serialize_aws_json_1_1(
                value["reason"]
            )
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> ValidationException_:
    out: ValidationException_ = {}  # type: ignore[typeddict-item]
    if data.get("Message") is not None:
        out["message"] = data["Message"]
    if data.get("RequestId") is not None:
        out["request_id"] = data["RequestId"]
    if data.get("Reason") is not None:
        import capo_identitystore.types.validation_exception_reason

        out["reason"] = (
            capo_identitystore.types.validation_exception_reason.deserialize_aws_json_1_1(
                data["Reason"]
            )
        )
    return out


class ValidationException(ServiceError):
    """Modeled error for Smithy shape ``com.amazonaws.identitystore#ValidationException``."""

    code: str | None = "ValidationException"

    def __init__(self, data: ValidationException_, message: str | None = None):
        super().__init__(
            "client",
            is_throttling_error=False,
            is_retryable=False,
            code="ValidationException",
            message=message if message is not None else data.get("message"),
        )
        self.data = data

    @classmethod
    def from_aws_json_1_1(
        cls, data: dict, message: str | None = None
    ) -> "ValidationException":
        return cls(deserialize_aws_json_1_1(data), message)
