"""Generated from Smithy shape ``com.amazonaws.bedrockagentcorecontrol#PrivateKeyJwtConfig``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_bedrock_agentcore_control.types.additional_claims
    import capo_bedrock_agentcore_control.types.private_key_source
    import capo_bedrock_agentcore_control.types.signing_algorithm


class PrivateKeyJwtConfig(TypedDict, closed=True):
    private_key_source: NotRequired[
        "capo_bedrock_agentcore_control.types.private_key_source.PrivateKeySource"
    ]
    """<p>The private key source for the JWT client assertion.</p>"""
    signing_algorithm: NotRequired[
        "capo_bedrock_agentcore_control.types.signing_algorithm.SigningAlgorithm"
    ]
    """<p>The algorithm used to sign the JWT client assertion. Valid values are <code>RS256</code>, <code>PS256</code>, and <code>ES256</code>.</p>"""
    additional_header_claims: NotRequired[
        "capo_bedrock_agentcore_control.types.additional_claims.AdditionalClaims"
    ]
    """<p>A map of additional claims to include in the JWT client assertion header. Standard header claims such as <code>alg</code> and <code>typ</code> cannot be added.</p>"""
    additional_payload_claims: NotRequired[
        "capo_bedrock_agentcore_control.types.additional_claims.AdditionalClaims"
    ]
    """<p>A map of additional claims to include in the JWT client assertion payload. Payload claims generated by the service, such as <code>iss</code>, <code>sub</code>, <code>jti</code>, and <code>exp</code>, cannot be added.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: PrivateKeyJwtConfig) -> dict:
    out: dict = {}
    if "private_key_source" in value:
        import capo_bedrock_agentcore_control.types.private_key_source

        out["privateKeySource"] = (
            capo_bedrock_agentcore_control.types.private_key_source.serialize_json(
                value["private_key_source"]
            )
        )
    if "signing_algorithm" in value:
        import capo_bedrock_agentcore_control.types.signing_algorithm

        out["signingAlgorithm"] = (
            capo_bedrock_agentcore_control.types.signing_algorithm.serialize_json(
                value["signing_algorithm"]
            )
        )
    if "additional_header_claims" in value:
        import capo_bedrock_agentcore_control.types.additional_claims

        out["additionalHeaderClaims"] = (
            capo_bedrock_agentcore_control.types.additional_claims.serialize_json(
                value["additional_header_claims"]
            )
        )
    if "additional_payload_claims" in value:
        import capo_bedrock_agentcore_control.types.additional_claims

        out["additionalPayloadClaims"] = (
            capo_bedrock_agentcore_control.types.additional_claims.serialize_json(
                value["additional_payload_claims"]
            )
        )
    return out


def deserialize_json(data: dict) -> PrivateKeyJwtConfig:
    out: PrivateKeyJwtConfig = {}  # type: ignore[typeddict-item]
    if data.get("privateKeySource") is not None:
        import capo_bedrock_agentcore_control.types.private_key_source

        out["private_key_source"] = (
            capo_bedrock_agentcore_control.types.private_key_source.deserialize_json(
                data["privateKeySource"]
            )
        )
    if data.get("signingAlgorithm") is not None:
        import capo_bedrock_agentcore_control.types.signing_algorithm

        out["signing_algorithm"] = (
            capo_bedrock_agentcore_control.types.signing_algorithm.deserialize_json(
                data["signingAlgorithm"]
            )
        )
    if data.get("additionalHeaderClaims") is not None:
        import capo_bedrock_agentcore_control.types.additional_claims

        out["additional_header_claims"] = (
            capo_bedrock_agentcore_control.types.additional_claims.deserialize_json(
                data["additionalHeaderClaims"]
            )
        )
    if data.get("additionalPayloadClaims") is not None:
        import capo_bedrock_agentcore_control.types.additional_claims

        out["additional_payload_claims"] = (
            capo_bedrock_agentcore_control.types.additional_claims.deserialize_json(
                data["additionalPayloadClaims"]
            )
        )
    return out
