"""Generated from Smithy shape ``com.amazonaws.customerprofiles#SearchRecommendationsResponse``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_customer_profiles.types.recommendations
    import capo_customer_profiles.types.uuid


class SearchRecommendationsResponse(TypedDict, closed=True):
    profile_id: NotRequired["capo_customer_profiles.types.uuid.uuid"]
    """<p>The unique identifier of the profile for which to retrieve recommendations.</p>"""
    recommendations: NotRequired[
        "capo_customer_profiles.types.recommendations.Recommendations"
    ]
    """<p>List of recommendations generated by the recommender.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: SearchRecommendationsResponse) -> dict:
    out: dict = {}
    if "profile_id" in value:
        out["ProfileId"] = value["profile_id"]
    if "recommendations" in value:
        import capo_customer_profiles.types.recommendations

        out["Recommendations"] = (
            capo_customer_profiles.types.recommendations.serialize_json(
                value["recommendations"]
            )
        )
    return out


def deserialize_json(data: dict) -> SearchRecommendationsResponse:
    out: SearchRecommendationsResponse = {}  # type: ignore[typeddict-item]
    if data.get("ProfileId") is not None:
        out["profile_id"] = data["ProfileId"]
    if data.get("Recommendations") is not None:
        import capo_customer_profiles.types.recommendations

        out["recommendations"] = (
            capo_customer_profiles.types.recommendations.deserialize_json(
                data["Recommendations"]
            )
        )
    return out
