"""Generated from Smithy shape ``com.amazonaws.eventbridgev2#EventSourceArn``."""

from typing import TypeAlias

"""EventSource ARN: event-sourcev2/<type>/<name>/<id>. The type segment is set by the service (aws.service for AWS service events, aws.partner for partner events) and is not part of the resource's name. The id segment is a 25-character identifier generated by the service."""
EventSourceArn: TypeAlias = str
