"""Generated from Smithy shape ``com.amazonaws.redshiftdata#BatchExecuteStatementOutput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import datetime

    import capo_redshift_data.types.boxed_boolean
    import capo_redshift_data.types.boxed_long
    import capo_redshift_data.types.cluster_identifier_string
    import capo_redshift_data.types.db_group_list
    import capo_redshift_data.types.secret_arn
    import capo_redshift_data.types.statement_status_string
    import capo_redshift_data.types.string
    import capo_redshift_data.types.uuid
    import capo_redshift_data.types.workgroup_name_string


class BatchExecuteStatementOutput(TypedDict, closed=True):
    id: NotRequired["capo_redshift_data.types.uuid.UUID"]
    """<p>The identifier of the SQL statement whose results are to be fetched. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API. This identifier is returned by <code>BatchExecuteStatment</code>. </p>"""
    created_at: NotRequired["datetime.datetime"]
    """<p>The date and time (UTC) the statement was created. </p>"""
    cluster_identifier: NotRequired[
        "capo_redshift_data.types.cluster_identifier_string.ClusterIdentifierString"
    ]
    """<p>The cluster identifier. This element is not returned when connecting to a serverless workgroup. </p>"""
    db_user: NotRequired["capo_redshift_data.types.string.String"]
    """<p>The database user name.</p>"""
    db_groups: NotRequired["capo_redshift_data.types.db_group_list.DbGroupList"]
    """<p>A list of colon (:) separated names of database groups.</p>"""
    database: NotRequired["capo_redshift_data.types.string.String"]
    """<p>The name of the database.</p>"""
    secret_arn: NotRequired["capo_redshift_data.types.secret_arn.SecretArn"]
    """<p>The name or ARN of the secret that enables access to the database. </p>"""
    workgroup_name: NotRequired[
        "capo_redshift_data.types.workgroup_name_string.WorkgroupNameString"
    ]
    """<p>The serverless workgroup name or Amazon Resource Name (ARN). This element is not returned when connecting to a provisioned cluster.</p>"""
    session_id: NotRequired["capo_redshift_data.types.uuid.UUID"]
    """<p>The session identifier of the query.</p>"""
    status: NotRequired[
        "capo_redshift_data.types.statement_status_string.StatementStatusString"
    ]
    """<p>The status of the SQL statement. Status values are defined as follows: </p> <ul> <li> <p>ABORTED - The query run was stopped by the user. </p> </li> <li> <p>FAILED - The query run failed. </p> </li> <li> <p>FINISHED - The query has finished running. </p> </li> <li> <p>PICKED - The query has been chosen to be run. </p> </li> <li> <p>STARTED - The query run has started. </p> </li> <li> <p>SUBMITTED - The query was submitted, but not yet processed. </p> </li> </ul>"""
    redshift_pid: NotRequired["capo_redshift_data.types.boxed_long.BoxedLong"]
    """<p>The process identifier from Amazon Redshift. </p>"""
    has_result_set: NotRequired["capo_redshift_data.types.boxed_boolean.BoxedBoolean"]
    """<p>A value that indicates whether the statement has a result set. The result set can be empty. The value is true for an empty result set. The value is true if any substatement returns a result set.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: BatchExecuteStatementOutput) -> dict:
    out: dict = {}
    if "id" in value:
        out["Id"] = value["id"]
    if "created_at" in value:
        import capo_redshift_data.types._prelude.timestamp

        out["CreatedAt"] = (
            capo_redshift_data.types._prelude.timestamp.serialize_aws_json_1_1(
                value["created_at"]
            )
        )
    if "cluster_identifier" in value:
        out["ClusterIdentifier"] = value["cluster_identifier"]
    if "db_user" in value:
        out["DbUser"] = value["db_user"]
    if "db_groups" in value:
        import capo_redshift_data.types.db_group_list

        out["DbGroups"] = capo_redshift_data.types.db_group_list.serialize_aws_json_1_1(
            value["db_groups"]
        )
    if "database" in value:
        out["Database"] = value["database"]
    if "secret_arn" in value:
        out["SecretArn"] = value["secret_arn"]
    if "workgroup_name" in value:
        out["WorkgroupName"] = value["workgroup_name"]
    if "session_id" in value:
        out["SessionId"] = value["session_id"]
    if "status" in value:
        out["Status"] = value["status"]
    if "redshift_pid" in value:
        out["RedshiftPid"] = value["redshift_pid"]
    if "has_result_set" in value:
        out["HasResultSet"] = value["has_result_set"]
    return out


def deserialize_aws_json_1_1(data: dict) -> BatchExecuteStatementOutput:
    out: BatchExecuteStatementOutput = {}  # type: ignore[typeddict-item]
    if data.get("Id") is not None:
        out["id"] = data["Id"]
    if data.get("CreatedAt") is not None:
        import capo_redshift_data.types._prelude.timestamp

        out["created_at"] = (
            capo_redshift_data.types._prelude.timestamp.deserialize_aws_json_1_1(
                data["CreatedAt"]
            )
        )
    if data.get("ClusterIdentifier") is not None:
        out["cluster_identifier"] = data["ClusterIdentifier"]
    if data.get("DbUser") is not None:
        out["db_user"] = data["DbUser"]
    if data.get("DbGroups") is not None:
        import capo_redshift_data.types.db_group_list

        out["db_groups"] = (
            capo_redshift_data.types.db_group_list.deserialize_aws_json_1_1(
                data["DbGroups"]
            )
        )
    if data.get("Database") is not None:
        out["database"] = data["Database"]
    if data.get("SecretArn") is not None:
        out["secret_arn"] = data["SecretArn"]
    if data.get("WorkgroupName") is not None:
        out["workgroup_name"] = data["WorkgroupName"]
    if data.get("SessionId") is not None:
        out["session_id"] = data["SessionId"]
    if data.get("Status") is not None:
        out["status"] = data["Status"]
    if data.get("RedshiftPid") is not None:
        out["redshift_pid"] = data["RedshiftPid"]
    if data.get("HasResultSet") is not None:
        out["has_result_set"] = data["HasResultSet"]
    return out
