"""Generated from Smithy shape ``com.amazonaws.redshiftdata#DescribeStatementRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_redshift_data.errors import DeserializationError

if TYPE_CHECKING:
    import capo_redshift_data.types.uuid
    import capo_redshift_data.types.wait_time_seconds


class DescribeStatementRequest(TypedDict, closed=True):
    id: "capo_redshift_data.types.uuid.UUID"
    """<p>The identifier of the SQL statement to describe. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API. A suffix indicates the number of the SQL statement. For example, <code>d9b6c0c9-0747-4bf4-b142-e8883122f766:2</code> has a suffix of <code>:2</code> that indicates the second SQL statement of a batch query. This identifier is returned by <code>BatchExecuteStatment</code>, <code>ExecuteStatement</code>, and <code>ListStatements</code>. </p>"""
    wait_time_seconds: NotRequired[
        "capo_redshift_data.types.wait_time_seconds.WaitTimeSeconds"
    ]
    """<p>The number of seconds to wait for the SQL statement to complete execution before returning the description. The maximum value is 30 seconds.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: DescribeStatementRequest) -> dict:
    out: dict = {}
    out["Id"] = value["id"]
    if "wait_time_seconds" in value:
        out["WaitTimeSeconds"] = value["wait_time_seconds"]
    return out


def deserialize_aws_json_1_1(data: dict) -> DescribeStatementRequest:
    out: DescribeStatementRequest = {}  # type: ignore[typeddict-item]
    if data.get("Id") is not None:
        out["id"] = data["Id"]
    else:
        raise DeserializationError("DescribeStatementRequest.id required")
    if data.get("WaitTimeSeconds") is not None:
        out["wait_time_seconds"] = data["WaitTimeSeconds"]
    return out
