"""Generated from Smithy shape ``com.amazonaws.redshiftdata#ListSessionsRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_redshift_data.types.cluster_identifier_string
    import capo_redshift_data.types.list_statements_limit
    import capo_redshift_data.types.session_status_string
    import capo_redshift_data.types.string
    import capo_redshift_data.types.uuid
    import capo_redshift_data.types.workgroup_name_string


class ListSessionsRequest(TypedDict, closed=True):
    next_token: NotRequired["capo_redshift_data.types.string.String"]
    """<p>A value that indicates the starting point for the next set of response records in a subsequent request. If a value is returned in a response, you can retrieve the next set of records by providing this returned NextToken value in the next NextToken parameter and retrying the command. If the NextToken field is empty, all response records have been retrieved for the request.</p>"""
    max_results: "capo_redshift_data.types.list_statements_limit.ListStatementsLimit"
    """<p>The maximum number of sessions to return in the response. If more sessions exist than fit in one response, the operation returns <code>NextToken</code> to paginate the results.</p>"""
    session_id: NotRequired["capo_redshift_data.types.uuid.UUID"]
    """<p>The identifier of a specific session to return metadata for. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API. When you provide <code>SessionId</code>, you can't specify <code>Status</code>, <code>ClusterIdentifier</code>, <code>WorkgroupName</code>, or <code>Database</code>.</p>"""
    status: NotRequired[
        "capo_redshift_data.types.session_status_string.SessionStatusString"
    ]
    """<p>The status of the sessions to list. If no status is specified, sessions with a status of <code>AVAILABLE</code> or <code>BUSY</code> are returned. Status values are defined as follows:</p> <ul> <li> <p>AVAILABLE – The session is open and ready to run a SQL statement.</p> </li> <li> <p>BUSY – The session is currently running a SQL statement.</p> </li> <li> <p>CLOSED – The session is closed and can no longer run SQL statements.</p> </li> </ul>"""
    role_level: NotRequired["bool"]
    """<p>Specifies whether to return all sessions created by the caller's IAM role, including sessions from previous IAM sessions. If false, only sessions created in the current IAM session are returned. The default is true.</p>"""
    cluster_identifier: NotRequired[
        "capo_redshift_data.types.cluster_identifier_string.ClusterIdentifierString"
    ]
    """<p>The cluster identifier. Only sessions on this cluster are returned. When providing <code>ClusterIdentifier</code>, then <code>WorkgroupName</code> can't be specified.</p>"""
    workgroup_name: NotRequired[
        "capo_redshift_data.types.workgroup_name_string.WorkgroupNameString"
    ]
    """<p>The serverless workgroup name or Amazon Resource Name (ARN). Only sessions on this workgroup are returned. When providing <code>WorkgroupName</code>, then <code>ClusterIdentifier</code> can't be specified.</p>"""
    database: NotRequired["capo_redshift_data.types.string.String"]
    """<p>The name of the database. Only sessions connected to this database are returned.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListSessionsRequest) -> dict:
    out: dict = {}
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    out["MaxResults"] = value.get("max_results", 0)
    if "session_id" in value:
        out["SessionId"] = value["session_id"]
    if "status" in value:
        out["Status"] = value["status"]
    if "role_level" in value:
        out["RoleLevel"] = value["role_level"]
    if "cluster_identifier" in value:
        out["ClusterIdentifier"] = value["cluster_identifier"]
    if "workgroup_name" in value:
        out["WorkgroupName"] = value["workgroup_name"]
    if "database" in value:
        out["Database"] = value["database"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ListSessionsRequest:
    out: ListSessionsRequest = {}  # type: ignore[typeddict-item]
    if data.get("NextToken") is not None:
        out["next_token"] = data["NextToken"]
    if data.get("MaxResults") is not None:
        out["max_results"] = data["MaxResults"]
    else:
        out["max_results"] = 0
    if data.get("SessionId") is not None:
        out["session_id"] = data["SessionId"]
    if data.get("Status") is not None:
        out["status"] = data["Status"]
    if data.get("RoleLevel") is not None:
        out["role_level"] = data["RoleLevel"]
    if data.get("ClusterIdentifier") is not None:
        out["cluster_identifier"] = data["ClusterIdentifier"]
    if data.get("WorkgroupName") is not None:
        out["workgroup_name"] = data["WorkgroupName"]
    if data.get("Database") is not None:
        out["database"] = data["Database"]
    return out
