"""Generated from Smithy shape ``com.amazonaws.redshiftdata#SessionData``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_redshift_data.errors import DeserializationError

if TYPE_CHECKING:
    import datetime

    import capo_redshift_data.types.session_alive_seconds
    import capo_redshift_data.types.session_status_string
    import capo_redshift_data.types.string
    import capo_redshift_data.types.uuid
    import capo_redshift_data.types.workgroup_name_string


class SessionData(TypedDict, closed=True):
    session_id: "capo_redshift_data.types.uuid.UUID"
    """<p>The session identifier. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API.</p>"""
    status: "capo_redshift_data.types.session_status_string.SessionStatusString"
    """<p>The status of the session. Status values are defined as follows:</p> <ul> <li> <p>AVAILABLE – The session is open and ready to run a SQL statement.</p> </li> <li> <p>BUSY – The session is currently running a SQL statement.</p> </li> <li> <p>CLOSED – The session is closed and can no longer run SQL statements.</p> </li> </ul>"""
    created_at: "datetime.datetime"
    """<p>The date and time (UTC) when the session was created.</p>"""
    updated_at: NotRequired["datetime.datetime"]
    """<p>The date and time (UTC) that the session metadata was last updated. An example is the time the status last changed.</p>"""
    database: NotRequired["capo_redshift_data.types.string.String"]
    """<p>The name of the database that the session is connected to.</p>"""
    db_user: NotRequired["capo_redshift_data.types.string.String"]
    """<p>The database user name.</p>"""
    cluster_identifier: NotRequired["capo_redshift_data.types.string.String"]
    """<p>The cluster identifier. This element is not returned when connecting to a serverless workgroup.</p>"""
    workgroup_name: NotRequired[
        "capo_redshift_data.types.workgroup_name_string.WorkgroupNameString"
    ]
    """<p>The serverless workgroup name or Amazon Resource Name (ARN). This element is not returned when connecting to a provisioned cluster.</p>"""
    session_alive_seconds: NotRequired[
        "capo_redshift_data.types.session_alive_seconds.SessionAliveSeconds"
    ]
    """<p>The number of seconds that the session is kept alive after a query finishes.</p>"""
    session_ttl: NotRequired["datetime.datetime"]
    """<p>The date and time (UTC) when the session is set to expire and be closed.</p>"""
    current_statement_id: NotRequired["capo_redshift_data.types.uuid.UUID"]
    """<p>The identifier of the SQL statement currently running in the session. This value is a universally unique identifier (UUID) generated by Amazon Redshift Data API. This element is returned only when the session status is <code>BUSY</code>.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: SessionData) -> dict:
    out: dict = {}
    out["SessionId"] = value["session_id"]
    out["Status"] = value["status"]
    import capo_redshift_data.types._prelude.timestamp

    out["CreatedAt"] = (
        capo_redshift_data.types._prelude.timestamp.serialize_aws_json_1_1(
            value["created_at"]
        )
    )
    if "updated_at" in value:
        import capo_redshift_data.types._prelude.timestamp

        out["UpdatedAt"] = (
            capo_redshift_data.types._prelude.timestamp.serialize_aws_json_1_1(
                value["updated_at"]
            )
        )
    if "database" in value:
        out["Database"] = value["database"]
    if "db_user" in value:
        out["DbUser"] = value["db_user"]
    if "cluster_identifier" in value:
        out["ClusterIdentifier"] = value["cluster_identifier"]
    if "workgroup_name" in value:
        out["WorkgroupName"] = value["workgroup_name"]
    if "session_alive_seconds" in value:
        out["SessionAliveSeconds"] = value["session_alive_seconds"]
    if "session_ttl" in value:
        import capo_redshift_data.types._prelude.timestamp

        out["SessionTtl"] = (
            capo_redshift_data.types._prelude.timestamp.serialize_aws_json_1_1(
                value["session_ttl"]
            )
        )
    if "current_statement_id" in value:
        out["CurrentStatementId"] = value["current_statement_id"]
    return out


def deserialize_aws_json_1_1(data: dict) -> SessionData:
    out: SessionData = {}  # type: ignore[typeddict-item]
    if data.get("SessionId") is not None:
        out["session_id"] = data["SessionId"]
    else:
        raise DeserializationError("SessionData.session_id required")
    if data.get("Status") is not None:
        out["status"] = data["Status"]
    else:
        raise DeserializationError("SessionData.status required")
    if data.get("CreatedAt") is not None:
        import capo_redshift_data.types._prelude.timestamp

        out["created_at"] = (
            capo_redshift_data.types._prelude.timestamp.deserialize_aws_json_1_1(
                data["CreatedAt"]
            )
        )
    else:
        raise DeserializationError("SessionData.created_at required")
    if data.get("UpdatedAt") is not None:
        import capo_redshift_data.types._prelude.timestamp

        out["updated_at"] = (
            capo_redshift_data.types._prelude.timestamp.deserialize_aws_json_1_1(
                data["UpdatedAt"]
            )
        )
    if data.get("Database") is not None:
        out["database"] = data["Database"]
    if data.get("DbUser") is not None:
        out["db_user"] = data["DbUser"]
    if data.get("ClusterIdentifier") is not None:
        out["cluster_identifier"] = data["ClusterIdentifier"]
    if data.get("WorkgroupName") is not None:
        out["workgroup_name"] = data["WorkgroupName"]
    if data.get("SessionAliveSeconds") is not None:
        out["session_alive_seconds"] = data["SessionAliveSeconds"]
    if data.get("SessionTtl") is not None:
        import capo_redshift_data.types._prelude.timestamp

        out["session_ttl"] = (
            capo_redshift_data.types._prelude.timestamp.deserialize_aws_json_1_1(
                data["SessionTtl"]
            )
        )
    if data.get("CurrentStatementId") is not None:
        out["current_statement_id"] = data["CurrentStatementId"]
    return out
