"""Generated from Smithy shape ``com.amazonaws.backup#DescribeRestoreJobOutput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_backup.types.account_id
    import capo_backup.types.arn
    import capo_backup.types.boolean2
    import capo_backup.types.iam_role_arn
    import capo_backup.types.long
    import capo_backup.types.resource_type
    import capo_backup.types.restore_deletion_status
    import capo_backup.types.restore_job_creator
    import capo_backup.types.restore_job_status
    import capo_backup.types.restore_validation_status
    import capo_backup.types.string
    import capo_backup.types.timestamp


class DescribeRestoreJobOutput(TypedDict, closed=True):
    account_id: NotRequired["capo_backup.types.account_id.AccountId"]
    """<p>Returns the account ID that owns the restore job.</p>"""
    restore_job_id: NotRequired["capo_backup.types.string.string"]
    """<p>Uniquely identifies the job that restores a recovery point.</p>"""
    recovery_point_arn: NotRequired["capo_backup.types.arn.ARN"]
    """<p>An ARN that uniquely identifies a recovery point; for example, <code>arn:aws:backup:us-east-1:123456789012:recovery-point:1EB3B5E7-9EB0-435A-A80B-108B488B0D45</code>.</p>"""
    source_resource_arn: NotRequired["capo_backup.types.arn.ARN"]
    """<p>The Amazon Resource Name (ARN) of the original resource that was backed up. This provides context about what resource is being restored.</p>"""
    backup_vault_arn: NotRequired["capo_backup.types.arn.ARN"]
    """<p>The Amazon Resource Name (ARN) of the backup vault containing the recovery point being restored. This helps identify vault access policies and permissions.</p>"""
    creation_date: NotRequired["capo_backup.types.timestamp.timestamp"]
    """<p>The date and time that a restore job is created, in Unix format and Coordinated Universal Time (UTC). The value of <code>CreationDate</code> is accurate to milliseconds. For example, the value 1516925490.087 represents Friday, January 26, 2018 12:11:30.087 AM.</p>"""
    completion_date: NotRequired["capo_backup.types.timestamp.timestamp"]
    """<p>The date and time that a job to restore a recovery point is completed, in Unix format and Coordinated Universal Time (UTC). The value of <code>CompletionDate</code> is accurate to milliseconds. For example, the value 1516925490.087 represents Friday, January 26, 2018 12:11:30.087 AM.</p>"""
    status: NotRequired["capo_backup.types.restore_job_status.RestoreJobStatus"]
    """<p>Status code specifying the state of the job that is initiated by Backup to restore a recovery point.</p>"""
    status_message: NotRequired["capo_backup.types.string.string"]
    """<p>A message showing the status of a job to restore a recovery point.</p>"""
    percent_done: NotRequired["capo_backup.types.string.string"]
    """<p>Contains an estimated percentage that is complete of a job at the time the job status was queried.</p>"""
    backup_size_in_bytes: NotRequired["capo_backup.types.long.Long"]
    """<p>The size, in bytes, of the restored resource.</p>"""
    iam_role_arn: NotRequired["capo_backup.types.iam_role_arn.IAMRoleArn"]
    """<p>Specifies the IAM role ARN used to create the target recovery point; for example, <code>arn:aws:iam::123456789012:role/S3Access</code>.</p>"""
    expected_completion_time_minutes: NotRequired["capo_backup.types.long.Long"]
    """<p>The amount of time in minutes that a job restoring a recovery point is expected to take.</p>"""
    created_resource_arn: NotRequired["capo_backup.types.arn.ARN"]
    """<p>The Amazon Resource Name (ARN) of the resource that was created by the restore job.</p> <p>The format of the ARN depends on the resource type of the backed-up resource.</p>"""
    resource_type: NotRequired["capo_backup.types.resource_type.ResourceType"]
    """<p>Returns metadata associated with a restore job listed by resource type.</p>"""
    recovery_point_creation_date: NotRequired["capo_backup.types.timestamp.timestamp"]
    """<p>The creation date of the recovery point made by the specifed restore job.</p>"""
    created_by: NotRequired["capo_backup.types.restore_job_creator.RestoreJobCreator"]
    """<p>Contains identifying information about the creation of a restore job.</p>"""
    validation_status: NotRequired[
        "capo_backup.types.restore_validation_status.RestoreValidationStatus"
    ]
    """<p>The status of validation run on the indicated restore job.</p>"""
    validation_status_message: NotRequired["capo_backup.types.string.string"]
    """<p>The status message.</p>"""
    deletion_status: NotRequired[
        "capo_backup.types.restore_deletion_status.RestoreDeletionStatus"
    ]
    """<p>The status of the data generated by the restore test.</p>"""
    deletion_status_message: NotRequired["capo_backup.types.string.string"]
    """<p>This describes the restore job deletion status.</p>"""
    is_parent: "capo_backup.types.boolean2.Boolean2"
    """<p>This is a boolean value indicating whether the restore job is a parent (composite) restore job.</p>"""
    parent_job_id: NotRequired["capo_backup.types.string.string"]
    """<p>This is the unique identifier of the parent restore job for the selected restore job.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: DescribeRestoreJobOutput) -> dict:
    out: dict = {}
    if "account_id" in value:
        out["AccountId"] = value["account_id"]
    if "restore_job_id" in value:
        out["RestoreJobId"] = value["restore_job_id"]
    if "recovery_point_arn" in value:
        out["RecoveryPointArn"] = value["recovery_point_arn"]
    if "source_resource_arn" in value:
        out["SourceResourceArn"] = value["source_resource_arn"]
    if "backup_vault_arn" in value:
        out["BackupVaultArn"] = value["backup_vault_arn"]
    if "creation_date" in value:
        import capo_backup.types.timestamp

        out["CreationDate"] = capo_backup.types.timestamp.serialize_json(
            value["creation_date"]
        )
    if "completion_date" in value:
        import capo_backup.types.timestamp

        out["CompletionDate"] = capo_backup.types.timestamp.serialize_json(
            value["completion_date"]
        )
    if "status" in value:
        import capo_backup.types.restore_job_status

        out["Status"] = capo_backup.types.restore_job_status.serialize_json(
            value["status"]
        )
    if "status_message" in value:
        out["StatusMessage"] = value["status_message"]
    if "percent_done" in value:
        out["PercentDone"] = value["percent_done"]
    if "backup_size_in_bytes" in value:
        out["BackupSizeInBytes"] = value["backup_size_in_bytes"]
    if "iam_role_arn" in value:
        out["IamRoleArn"] = value["iam_role_arn"]
    if "expected_completion_time_minutes" in value:
        out["ExpectedCompletionTimeMinutes"] = value["expected_completion_time_minutes"]
    if "created_resource_arn" in value:
        out["CreatedResourceArn"] = value["created_resource_arn"]
    if "resource_type" in value:
        out["ResourceType"] = value["resource_type"]
    if "recovery_point_creation_date" in value:
        import capo_backup.types.timestamp

        out["RecoveryPointCreationDate"] = capo_backup.types.timestamp.serialize_json(
            value["recovery_point_creation_date"]
        )
    if "created_by" in value:
        import capo_backup.types.restore_job_creator

        out["CreatedBy"] = capo_backup.types.restore_job_creator.serialize_json(
            value["created_by"]
        )
    if "validation_status" in value:
        import capo_backup.types.restore_validation_status

        out["ValidationStatus"] = (
            capo_backup.types.restore_validation_status.serialize_json(
                value["validation_status"]
            )
        )
    if "validation_status_message" in value:
        out["ValidationStatusMessage"] = value["validation_status_message"]
    if "deletion_status" in value:
        import capo_backup.types.restore_deletion_status

        out["DeletionStatus"] = (
            capo_backup.types.restore_deletion_status.serialize_json(
                value["deletion_status"]
            )
        )
    if "deletion_status_message" in value:
        out["DeletionStatusMessage"] = value["deletion_status_message"]
    out["IsParent"] = value.get("is_parent", False)
    if "parent_job_id" in value:
        out["ParentJobId"] = value["parent_job_id"]
    return out


def deserialize_json(data: dict) -> DescribeRestoreJobOutput:
    out: DescribeRestoreJobOutput = {}  # type: ignore[typeddict-item]
    if data.get("AccountId") is not None:
        out["account_id"] = data["AccountId"]
    if data.get("RestoreJobId") is not None:
        out["restore_job_id"] = data["RestoreJobId"]
    if data.get("RecoveryPointArn") is not None:
        out["recovery_point_arn"] = data["RecoveryPointArn"]
    if data.get("SourceResourceArn") is not None:
        out["source_resource_arn"] = data["SourceResourceArn"]
    if data.get("BackupVaultArn") is not None:
        out["backup_vault_arn"] = data["BackupVaultArn"]
    if data.get("CreationDate") is not None:
        import capo_backup.types.timestamp

        out["creation_date"] = capo_backup.types.timestamp.deserialize_json(
            data["CreationDate"]
        )
    if data.get("CompletionDate") is not None:
        import capo_backup.types.timestamp

        out["completion_date"] = capo_backup.types.timestamp.deserialize_json(
            data["CompletionDate"]
        )
    if data.get("Status") is not None:
        import capo_backup.types.restore_job_status

        out["status"] = capo_backup.types.restore_job_status.deserialize_json(
            data["Status"]
        )
    if data.get("StatusMessage") is not None:
        out["status_message"] = data["StatusMessage"]
    if data.get("PercentDone") is not None:
        out["percent_done"] = data["PercentDone"]
    if data.get("BackupSizeInBytes") is not None:
        out["backup_size_in_bytes"] = data["BackupSizeInBytes"]
    if data.get("IamRoleArn") is not None:
        out["iam_role_arn"] = data["IamRoleArn"]
    if data.get("ExpectedCompletionTimeMinutes") is not None:
        out["expected_completion_time_minutes"] = data["ExpectedCompletionTimeMinutes"]
    if data.get("CreatedResourceArn") is not None:
        out["created_resource_arn"] = data["CreatedResourceArn"]
    if data.get("ResourceType") is not None:
        out["resource_type"] = data["ResourceType"]
    if data.get("RecoveryPointCreationDate") is not None:
        import capo_backup.types.timestamp

        out["recovery_point_creation_date"] = (
            capo_backup.types.timestamp.deserialize_json(
                data["RecoveryPointCreationDate"]
            )
        )
    if data.get("CreatedBy") is not None:
        import capo_backup.types.restore_job_creator

        out["created_by"] = capo_backup.types.restore_job_creator.deserialize_json(
            data["CreatedBy"]
        )
    if data.get("ValidationStatus") is not None:
        import capo_backup.types.restore_validation_status

        out["validation_status"] = (
            capo_backup.types.restore_validation_status.deserialize_json(
                data["ValidationStatus"]
            )
        )
    if data.get("ValidationStatusMessage") is not None:
        out["validation_status_message"] = data["ValidationStatusMessage"]
    if data.get("DeletionStatus") is not None:
        import capo_backup.types.restore_deletion_status

        out["deletion_status"] = (
            capo_backup.types.restore_deletion_status.deserialize_json(
                data["DeletionStatus"]
            )
        )
    if data.get("DeletionStatusMessage") is not None:
        out["deletion_status_message"] = data["DeletionStatusMessage"]
    if data.get("IsParent") is not None:
        out["is_parent"] = data["IsParent"]
    else:
        out["is_parent"] = False
    if data.get("ParentJobId") is not None:
        out["parent_job_id"] = data["ParentJobId"]
    return out
