"""Generated from Smithy shape ``com.amazonaws.qbusiness#InstructionCollection``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_qbusiness.types.instruction


class InstructionCollection(TypedDict, closed=True):
    response_length: NotRequired["capo_qbusiness.types.instruction.Instruction"]
    """<p>Specifies the desired length of responses generated by Amazon Q Business. This parameter allows administrators to control whether responses are concise and brief or more detailed and comprehensive.</p>"""
    target_audience: NotRequired["capo_qbusiness.types.instruction.Instruction"]
    """<p>Defines the intended audience for the responses, allowing Amazon Q Business to tailor its language, terminology, and explanations appropriately. This could range from technical experts to general users with varying levels of domain knowledge.</p>"""
    perspective: NotRequired["capo_qbusiness.types.instruction.Instruction"]
    """<p>Determines the point of view or perspective from which Amazon Q Business generates responses, such as first-person, second-person, or third-person perspective, affecting how information is presented to users.</p>"""
    output_style: NotRequired["capo_qbusiness.types.instruction.Instruction"]
    """<p>Specifies the formatting and structural style of responses, such as bullet points, paragraphs, step-by-step instructions, or other organizational formats that enhance readability and comprehension.</p>"""
    identity: NotRequired["capo_qbusiness.types.instruction.Instruction"]
    """<p>Defines the persona or identity that Amazon Q Business should adopt when responding to users, allowing for customization of the assistant's character, role, or representation within an organization.</p>"""
    tone: NotRequired["capo_qbusiness.types.instruction.Instruction"]
    """<p>Controls the emotional tone and communication style of responses, such as formal, casual, technical, friendly, or professional, to align with organizational communication standards and user expectations.</p>"""
    custom_instructions: NotRequired["capo_qbusiness.types.instruction.Instruction"]
    """<p>Allows administrators to provide specific, custom instructions that guide how Amazon Q Business should respond in particular scenarios or to certain types of queries, enabling fine-grained control over response generation.</p>"""
    examples: NotRequired["capo_qbusiness.types.instruction.Instruction"]
    """<p>Provides sample responses or templates that Amazon Q Business can reference when generating responses, helping to establish consistent patterns and formats for different types of user queries.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: InstructionCollection) -> dict:
    out: dict = {}
    if "response_length" in value:
        out["responseLength"] = value["response_length"]
    if "target_audience" in value:
        out["targetAudience"] = value["target_audience"]
    if "perspective" in value:
        out["perspective"] = value["perspective"]
    if "output_style" in value:
        out["outputStyle"] = value["output_style"]
    if "identity" in value:
        out["identity"] = value["identity"]
    if "tone" in value:
        out["tone"] = value["tone"]
    if "custom_instructions" in value:
        out["customInstructions"] = value["custom_instructions"]
    if "examples" in value:
        out["examples"] = value["examples"]
    return out


def deserialize_json(data: dict) -> InstructionCollection:
    out: InstructionCollection = {}  # type: ignore[typeddict-item]
    if data.get("responseLength") is not None:
        out["response_length"] = data["responseLength"]
    if data.get("targetAudience") is not None:
        out["target_audience"] = data["targetAudience"]
    if data.get("perspective") is not None:
        out["perspective"] = data["perspective"]
    if data.get("outputStyle") is not None:
        out["output_style"] = data["outputStyle"]
    if data.get("identity") is not None:
        out["identity"] = data["identity"]
    if data.get("tone") is not None:
        out["tone"] = data["tone"]
    if data.get("customInstructions") is not None:
        out["custom_instructions"] = data["customInstructions"]
    if data.get("examples") is not None:
        out["examples"] = data["examples"]
    return out
