"""Generated from Smithy shape ``com.amazonaws.guardduty#RuleDetail``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_guardduty.types.detection_rule_arn
    import capo_guardduty.types.detection_rule_data_source
    import capo_guardduty.types.detection_rule_description
    import capo_guardduty.types.detection_rule_service_name
    import capo_guardduty.types.detection_rule_severity
    import capo_guardduty.types.mitre_tactic
    import capo_guardduty.types.mitre_technique
    import capo_guardduty.types.rule_definition
    import capo_guardduty.types.rule_id
    import capo_guardduty.types.rule_language
    import capo_guardduty.types.rule_name
    import capo_guardduty.types.rule_schema
    import capo_guardduty.types.timestamp


class RuleDetail(TypedDict, closed=True):
    rule_id: NotRequired["capo_guardduty.types.rule_id.RuleId"]
    """<p>The unique identifier for the rule.</p>"""
    arn: NotRequired["capo_guardduty.types.detection_rule_arn.DetectionRuleArn"]
    """<p>The Amazon Resource Name (ARN) of the rule.</p>"""
    name: NotRequired["capo_guardduty.types.rule_name.RuleName"]
    """<p>The display name of the rule.</p>"""
    description: NotRequired[
        "capo_guardduty.types.detection_rule_description.DetectionRuleDescription"
    ]
    """<p>A description of what the rule detects.</p>"""
    severity: NotRequired[
        "capo_guardduty.types.detection_rule_severity.DetectionRuleSeverity"
    ]
    """<p>The severity level assigned to findings generated by this rule.</p>"""
    data_source: NotRequired[
        "capo_guardduty.types.detection_rule_data_source.DetectionRuleDataSource"
    ]
    """<p>The data source that the rule analyzes.</p>"""
    tactic: NotRequired["capo_guardduty.types.mitre_tactic.MitreTactic"]
    """<p>The MITRE ATT&amp;CK tactic associated with the rule.</p>"""
    technique: NotRequired["capo_guardduty.types.mitre_technique.MitreTechnique"]
    """<p>The MITRE ATT&amp;CK technique associated with the rule.</p>"""
    service: NotRequired[
        "capo_guardduty.types.detection_rule_service_name.DetectionRuleServiceName"
    ]
    """<p>The Amazon Web Services service associated with the rule.</p>"""
    definition: NotRequired["capo_guardduty.types.rule_definition.RuleDefinition"]
    """<p>The detection logic definition for the rule.</p>"""
    language: NotRequired["capo_guardduty.types.rule_language.RuleLanguage"]
    """<p>The language used for the detection logic expression.</p>"""
    schema: NotRequired["capo_guardduty.types.rule_schema.RuleSchema"]
    """<p>The schema version used by the rule definition.</p>"""
    created_at: NotRequired["capo_guardduty.types.timestamp.Timestamp"]
    """<p>The timestamp when the rule was created.</p>"""
    updated_at: NotRequired["capo_guardduty.types.timestamp.Timestamp"]
    """<p>The timestamp when the rule was last updated.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: RuleDetail) -> dict:
    out: dict = {}
    if "rule_id" in value:
        out["ruleId"] = value["rule_id"]
    if "arn" in value:
        out["arn"] = value["arn"]
    if "name" in value:
        out["name"] = value["name"]
    if "description" in value:
        out["description"] = value["description"]
    if "severity" in value:
        import capo_guardduty.types.detection_rule_severity

        out["severity"] = capo_guardduty.types.detection_rule_severity.serialize_json(
            value["severity"]
        )
    if "data_source" in value:
        import capo_guardduty.types.detection_rule_data_source

        out["dataSource"] = (
            capo_guardduty.types.detection_rule_data_source.serialize_json(
                value["data_source"]
            )
        )
    if "tactic" in value:
        out["tactic"] = value["tactic"]
    if "technique" in value:
        out["technique"] = value["technique"]
    if "service" in value:
        out["service"] = value["service"]
    if "definition" in value:
        import capo_guardduty.types.rule_definition

        out["definition"] = capo_guardduty.types.rule_definition.serialize_json(
            value["definition"]
        )
    if "language" in value:
        import capo_guardduty.types.rule_language

        out["language"] = capo_guardduty.types.rule_language.serialize_json(
            value["language"]
        )
    if "schema" in value:
        import capo_guardduty.types.rule_schema

        out["schema"] = capo_guardduty.types.rule_schema.serialize_json(value["schema"])
    if "created_at" in value:
        import capo_guardduty.types.timestamp

        out["createdAt"] = capo_guardduty.types.timestamp.serialize_json(
            value["created_at"]
        )
    if "updated_at" in value:
        import capo_guardduty.types.timestamp

        out["updatedAt"] = capo_guardduty.types.timestamp.serialize_json(
            value["updated_at"]
        )
    return out


def deserialize_json(data: dict) -> RuleDetail:
    out: RuleDetail = {}  # type: ignore[typeddict-item]
    if data.get("ruleId") is not None:
        out["rule_id"] = data["ruleId"]
    if data.get("arn") is not None:
        out["arn"] = data["arn"]
    if data.get("name") is not None:
        out["name"] = data["name"]
    if data.get("description") is not None:
        out["description"] = data["description"]
    if data.get("severity") is not None:
        import capo_guardduty.types.detection_rule_severity

        out["severity"] = capo_guardduty.types.detection_rule_severity.deserialize_json(
            data["severity"]
        )
    if data.get("dataSource") is not None:
        import capo_guardduty.types.detection_rule_data_source

        out["data_source"] = (
            capo_guardduty.types.detection_rule_data_source.deserialize_json(
                data["dataSource"]
            )
        )
    if data.get("tactic") is not None:
        out["tactic"] = data["tactic"]
    if data.get("technique") is not None:
        out["technique"] = data["technique"]
    if data.get("service") is not None:
        out["service"] = data["service"]
    if data.get("definition") is not None:
        import capo_guardduty.types.rule_definition

        out["definition"] = capo_guardduty.types.rule_definition.deserialize_json(
            data["definition"]
        )
    if data.get("language") is not None:
        import capo_guardduty.types.rule_language

        out["language"] = capo_guardduty.types.rule_language.deserialize_json(
            data["language"]
        )
    if data.get("schema") is not None:
        import capo_guardduty.types.rule_schema

        out["schema"] = capo_guardduty.types.rule_schema.deserialize_json(
            data["schema"]
        )
    if data.get("createdAt") is not None:
        import capo_guardduty.types.timestamp

        out["created_at"] = capo_guardduty.types.timestamp.deserialize_json(
            data["createdAt"]
        )
    if data.get("updatedAt") is not None:
        import capo_guardduty.types.timestamp

        out["updated_at"] = capo_guardduty.types.timestamp.deserialize_json(
            data["updatedAt"]
        )
    return out
