"""Generated from Smithy shape ``com.amazonaws.neptunedata#StartMLModelTransformJobInput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_neptunedata.errors import DeserializationError

if TYPE_CHECKING:
    import capo_neptunedata.types.custom_model_transform_parameters
    import capo_neptunedata.types.string_list


class StartMLModelTransformJobInput(TypedDict, closed=True):
    id: NotRequired["str"]
    """<p>A unique identifier for the new job. The default is an autogenerated UUID.</p>"""
    data_processing_job_id: NotRequired["str"]
    """<p>The job ID of a completed data-processing job. You must include either <code>dataProcessingJobId</code> and a <code>mlModelTrainingJobId</code>, or a <code>trainingJobName</code>.</p>"""
    ml_model_training_job_id: NotRequired["str"]
    """<p>The job ID of a completed model-training job. You must include either <code>dataProcessingJobId</code> and a <code>mlModelTrainingJobId</code>, or a <code>trainingJobName</code>.</p>"""
    training_job_name: NotRequired["str"]
    """<p>The name of a completed SageMaker training job. You must include either <code>dataProcessingJobId</code> and a <code>mlModelTrainingJobId</code>, or a <code>trainingJobName</code>.</p>"""
    model_transform_output_s3_location: "str"
    """<p>The location in Amazon S3 where the model artifacts are to be stored.</p>"""
    sagemaker_iam_role_arn: NotRequired["str"]
    """<p>The ARN of an IAM role for SageMaker execution. This must be listed in your DB cluster parameter group or an error will occur.</p>"""
    neptune_iam_role_arn: NotRequired["str"]
    """<p>The ARN of an IAM role that provides Neptune access to SageMaker and Amazon S3 resources. This must be listed in your DB cluster parameter group or an error will occur.</p>"""
    custom_model_transform_parameters: NotRequired[
        "capo_neptunedata.types.custom_model_transform_parameters.CustomModelTransformParameters"
    ]
    """<p>Configuration information for a model transform using a custom model. The <code>customModelTransformParameters</code> object contains the following fields, which must have values compatible with the saved model parameters from the training job:</p>"""
    base_processing_instance_type: NotRequired["str"]
    """<p>The type of ML instance used in preparing and managing training of ML models. This is an ML compute instance chosen based on memory requirements for processing the training data and model.</p>"""
    base_processing_instance_volume_size_in_gb: NotRequired["int"]
    """<p>The disk volume size of the training instance in gigabytes. The default is 0. Both input data and the output model are stored on disk, so the volume size must be large enough to hold both data sets. If not specified or 0, Neptune ML selects a disk volume size based on the recommendation generated in the data processing step.</p>"""
    subnets: NotRequired["capo_neptunedata.types.string_list.StringList"]
    """<p>The IDs of the subnets in the Neptune VPC. The default is None.</p>"""
    security_group_ids: NotRequired["capo_neptunedata.types.string_list.StringList"]
    """<p>The VPC security group IDs. The default is None.</p>"""
    volume_encryption_kms_key: NotRequired["str"]
    """<p>The Amazon Key Management Service (KMS) key that SageMaker uses to encrypt data on the storage volume attached to the ML compute instances that run the training job. The default is None.</p>"""
    s3_output_encryption_kms_key: NotRequired["str"]
    """<p>The Amazon Key Management Service (KMS) key that SageMaker uses to encrypt the output of the processing job. The default is none.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: StartMLModelTransformJobInput) -> dict:
    out: dict = {}
    if "id" in value:
        out["id"] = value["id"]
    if "data_processing_job_id" in value:
        out["dataProcessingJobId"] = value["data_processing_job_id"]
    if "ml_model_training_job_id" in value:
        out["mlModelTrainingJobId"] = value["ml_model_training_job_id"]
    if "training_job_name" in value:
        out["trainingJobName"] = value["training_job_name"]
    out["modelTransformOutputS3Location"] = value["model_transform_output_s3_location"]
    if "sagemaker_iam_role_arn" in value:
        out["sagemakerIamRoleArn"] = value["sagemaker_iam_role_arn"]
    if "neptune_iam_role_arn" in value:
        out["neptuneIamRoleArn"] = value["neptune_iam_role_arn"]
    if "custom_model_transform_parameters" in value:
        import capo_neptunedata.types.custom_model_transform_parameters

        out["customModelTransformParameters"] = (
            capo_neptunedata.types.custom_model_transform_parameters.serialize_json(
                value["custom_model_transform_parameters"]
            )
        )
    if "base_processing_instance_type" in value:
        out["baseProcessingInstanceType"] = value["base_processing_instance_type"]
    if "base_processing_instance_volume_size_in_gb" in value:
        out["baseProcessingInstanceVolumeSizeInGB"] = value[
            "base_processing_instance_volume_size_in_gb"
        ]
    if "subnets" in value:
        import capo_neptunedata.types.string_list

        out["subnets"] = capo_neptunedata.types.string_list.serialize_json(
            value["subnets"]
        )
    if "security_group_ids" in value:
        import capo_neptunedata.types.string_list

        out["securityGroupIds"] = capo_neptunedata.types.string_list.serialize_json(
            value["security_group_ids"]
        )
    if "volume_encryption_kms_key" in value:
        out["volumeEncryptionKMSKey"] = value["volume_encryption_kms_key"]
    if "s3_output_encryption_kms_key" in value:
        out["s3OutputEncryptionKMSKey"] = value["s3_output_encryption_kms_key"]
    return out


def deserialize_json(data: dict) -> StartMLModelTransformJobInput:
    out: StartMLModelTransformJobInput = {}  # type: ignore[typeddict-item]
    if data.get("id") is not None:
        out["id"] = data["id"]
    if data.get("dataProcessingJobId") is not None:
        out["data_processing_job_id"] = data["dataProcessingJobId"]
    if data.get("mlModelTrainingJobId") is not None:
        out["ml_model_training_job_id"] = data["mlModelTrainingJobId"]
    if data.get("trainingJobName") is not None:
        out["training_job_name"] = data["trainingJobName"]
    if data.get("modelTransformOutputS3Location") is not None:
        out["model_transform_output_s3_location"] = data[
            "modelTransformOutputS3Location"
        ]
    else:
        raise DeserializationError(
            "StartMLModelTransformJobInput.model_transform_output_s3_location required"
        )
    if data.get("sagemakerIamRoleArn") is not None:
        out["sagemaker_iam_role_arn"] = data["sagemakerIamRoleArn"]
    if data.get("neptuneIamRoleArn") is not None:
        out["neptune_iam_role_arn"] = data["neptuneIamRoleArn"]
    if data.get("customModelTransformParameters") is not None:
        import capo_neptunedata.types.custom_model_transform_parameters

        out["custom_model_transform_parameters"] = (
            capo_neptunedata.types.custom_model_transform_parameters.deserialize_json(
                data["customModelTransformParameters"]
            )
        )
    if data.get("baseProcessingInstanceType") is not None:
        out["base_processing_instance_type"] = data["baseProcessingInstanceType"]
    if data.get("baseProcessingInstanceVolumeSizeInGB") is not None:
        out["base_processing_instance_volume_size_in_gb"] = data[
            "baseProcessingInstanceVolumeSizeInGB"
        ]
    if data.get("subnets") is not None:
        import capo_neptunedata.types.string_list

        out["subnets"] = capo_neptunedata.types.string_list.deserialize_json(
            data["subnets"]
        )
    if data.get("securityGroupIds") is not None:
        import capo_neptunedata.types.string_list

        out["security_group_ids"] = capo_neptunedata.types.string_list.deserialize_json(
            data["securityGroupIds"]
        )
    if data.get("volumeEncryptionKMSKey") is not None:
        out["volume_encryption_kms_key"] = data["volumeEncryptionKMSKey"]
    if data.get("s3OutputEncryptionKMSKey") is not None:
        out["s3_output_encryption_kms_key"] = data["s3OutputEncryptionKMSKey"]
    return out
